Backup/FinalDemo/Models/BoViewModel.cs
using FinalDemo.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FinalDemo.Models
{
    public class BoViewModel
    {
        public List<Bo> Bos;
    }
}

Backup/FinalDemo/Controllers/BoController.cs
using FinalDemo.Domain.Abtracts;
using FinalDemo.Domain.Entities;
using FinalDemo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace FinalDemo.Controllers
{
    public class BoController : BaseController
    {
        private IBoRepository repositoryBo { get; set; }
        private ILopRepository repositoryLop { get; set; }
        public ActionResult Index()
        {
            return View();
        }
        public BoController(IBoRepository repoBo, ILopRepository repoLop)
        {
            repositoryBo = repoBo;
            repositoryLop = repoLop;
            base.Init();
        }
        public ActionResult IndexBo(string searchTerm)
        {
            if (string.IsNullOrEmpty(searchTerm))
            {
                BoViewModel model = new BoViewModel();
                model.Bos = repositoryBo.GetAllBo();
                return View(model);
            }
            else
            {
                BoViewModel model = new BoViewModel();
                model.Bos = repositoryBo.SelectBy(searchTerm);
                return View(model);
            }
        }
        public PartialViewResult SignInOutPanel()
        {
            return PartialView(base.CurrentUser);
        }
        public ActionResult CreateNewBo()
        {
            if (base.Auth())
            {
                LopViewModel lopView = new LopViewModel();
                lopView.Lops = repositoryLop.GetAllLop();
                ViewBag.ListOfCodes = new SelectList(lopView.Lops, "MaLop", "TenTV");
                ViewBag.Codes = "C";
                return View();
            }
            else
            {
                return RedirectToAction("ResponseServer", "Home");
            }
        }
        [HttpPost]
        public ActionResult CreateNewBo(Bo bo)
        {
            // tránh TH đặc biệt gõ đúng id
            if (base.Auth())
            {
                if (Request.Cookies["groupId"].Value.LastIndexOf("4") == 4) 
                {
                    bo.Khoa = 0;
                }
                else
                {
                    bo.Khoa = -1;
                }
                bo.TenNguoiTao = base.CurrentUser.Ten;
                bo.NgayDangBai = DateTime.Now;
                bo.MaNguoiTao = base.CurrentUser.MaTaiKhoan;
                int res = repositoryBo.CreateNewBo(bo);
                return RedirectToAction("CacBaiDang", "QuanLyCaNhan");
            }
            else
            {
                return RedirectToAction("ResponseServer", "Home");
            }
        }
        public ActionResult Delete(int id)
        {
            if (base.Auth())
            {
                int res = repositoryBo.DeleteBo(id, base.CurrentUser.MaTaiKhoan);
                if (res != 0)
                {
                    return RedirectToAction("CacBaiDang", "QuanLyCaNhan");
                }                    
                return RedirectToAction("ResponseServer", "Home");
            }
            else
            {
                return RedirectToAction("ResponseServer", "Home");
            }
        }
        public ActionResult EditEmpty(int id)
        {
            if (base.Auth())
            {
                BoViewModel boView = new BoViewModel();
                boView.Bos = repositoryBo.SelectByID(id, base.CurrentUser.MaTaiKhoan);
                if (boView.Bos.Count > 0)
                {
                    return View(boView);
                }
                else { 
                    return RedirectToAction("ResponseServer", "Home");
                }
            }
            else
            {
                return RedirectToAction("ResponseServer", "Home");
            }
        }
        [HttpPost]
        public ActionResult EditEmpty(Bo bo)
        {
            if (base.Auth())
            {
                int res = repositoryBo.EditBo(bo);
                return RedirectToAction("CacBaiDang", "QuanLyCaNhan");
            }
            else
            {
                return RedirectToAction("ResponseServer", "Home");
            }
        }
        public ActionResult Details(int id)
        {
            //if (base.Auth())
            //{
                BoViewModel model = new BoViewModel();
                model.Bos = repositoryBo.SelectByID(id);
                return View(model);
            //}
            //else
            //{
            //    return RedirectToAction("ResponseServer", "Home");
            //}
        }
        public ActionResult Search(string searchTerm)
        {
            BoViewModel model = new BoViewModel();
            model.Bos = repositoryBo.SelectBy(searchTerm);
            return View(model);
        }
        public JsonResult SearchAuto(string term)
        {
            List<string> data;
            data = repositoryBo.SelectAuto(term);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
    }
}

Backup/FinalDemo/Views/Bo/CreateNewBo.cshtml
@model FinalDemo.Domain.Entities.Bo
@{
    Layout = "~/Views/Share/Index.cshtml";
}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Tạo mới Bộ</title>

    <link rel="stylesheet" href="/Contents/bootstrap.min.css" />
    <script src="~/Scripts/jquery-ui.js"></script>
    <script src="~/Scripts/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="/Contents/jquery-ui.min.css" />
</head>
<body>
    <div class="main">
        @using (Html.BeginForm("CreateNewBo", "Bo"))
        {
            <fieldset>
                <legend class="title">Tạo mới Bộ</legend>

                @Html.AntiForgeryToken()

                @Html.ValidationSummary(true)
                <div class="info-addnew">
                    <div class="editor-label">
                        Kí hiệu
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.KiHieu)
                        @Html.ValidationMessageFor(model => model.KiHieu)
                    </div>
                    <div class="editor-label">
                        Lớp
                    </div>
                    <div class="editor-field">
                        @Html.DropDownListFor(model => model.Lop, ViewBag.ListOfCodes as SelectList, "")
                        @Html.ValidationMessageFor(model => model.Lop)
                    </div>
                    <div class="editor-label">
                        Danh pháp khoa học
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.DPKH)
                        @Html.ValidationMessageFor(model => model.DPKH)
                    </div>

                    <div class="editor-label">
                        Tên tiếng Việt
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.TenTV)
                        @Html.ValidationMessageFor(model => model.TenTV)
                    </div>

                    <div class="editor-label">
                        Người phát hiện
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.NguoiPH)
                        @Html.ValidationMessageFor(model => model.NguoiPH)
                    </div>

                    <div class="editor-label">
                        Năm phát hiện
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.NamPH)
                        @Html.ValidationMessageFor(model => model.NamPH)
                    </div>
                    <div class="editor-field">
                        Ngày Cập nhật
                        @Html.TextBoxFor(model => model.NgayCapNhat, new { @class = "form-control datepicker", placeholder = "Chọn ngày..." })
                        @Html.ValidationMessageFor(model => model.NgayCapNhat)
                    </div>
                    <p>
                        <input type="submit" value="Tạo mới" />
                    </p>
                </div>
            </fieldset>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
    <script type="text/javascript">
        $(function () { // will trigger when the document is ready
            $('.datepicker').datepicker({
                changeMonth: true,
                changeYear: true,
                dateFormat: 'yy-mm-dd',
                showStatus: true,
                showWeeks: true,
                highlightWeek: true,
                numberOfMonths: 1,
                showAnim: "scale",
                showOptions: {
                    origin: ["top", "left"]
                }
            }); //Initialise any date pickers

        });
    </script>
</body>
</html>

Backup/FinalDemo/Views/Bo/Details.cshtml
@model FinalDemo.Models.BoViewModel

@{
    Layout = "~/Views/Share/Index.cshtml";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="/Contents/bootstrap.min.css" />
    <script src="/Scripts/jquery-1.11.1.min.js"></script>
    <script src="/Scripts/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="/Contents/jquery-ui.min.css" />
    <title>Chi tiết</title>

</head>
<body>


    <table class="table table-hover">
        <tr>
            <th>
                Danh pháp khoa học
            </th>
            <th>
                Tên tiếng Việt
            </th>
            <th>
                Người phát hiện
            </th>
            <th>
                Năm phát hiện
            </th>
            <th>
                Thao tác
            </th>
        </tr>
        @foreach (var item in Model.Bos)
        {

            <tr>
                <td>@Html.DisplayFor(modelId => item.DPKH)</td>

                <td>
                    @Html.DisplayFor(modelId => item.TenTV)
                </td>

                <td>
                    @Html.DisplayFor(modelId => item.NguoiPH)
                </td>

                <td>
                    @Html.DisplayFor(modelId => item.NamPH)
                </td>

                <td>
                    @Html.ActionLink("Edit", "EditEmpty", new { id = item.MaBo }) | @Html.ActionLink("Back to List", "IndexBo")
                </td>
            </tr>
        }
    </table>
</body>
</html>

Backup/FinalDemo/Views/Bo/Edit.cshtml
@model  FinalDemo.Models.BoViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit","Bo")) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Bo</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.MaBo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MaBo)
            @Html.ValidationMessageFor(model => model.MaBo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.KiHieu)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.KiHieu)
            @Html.ValidationMessageFor(model => model.KiHieu)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DPKH)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DPKH)
            @Html.ValidationMessageFor(model => model.DPKH)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.TenTV)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TenTV)
            @Html.ValidationMessageFor(model => model.TenTV)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NguoiPH)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NguoiPH)
            @Html.ValidationMessageFor(model => model.NguoiPH)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NamPH)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NamPH)
            @Html.ValidationMessageFor(model => model.NamPH)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Backup/FinalDemo/Views/Bo/EditEmpty.cshtml
@model  FinalDemo.Models.BoViewModel
<link rel="stylesheet" href="/Contents/bootstrap.min.css" />
<script src="/Scripts/jquery-1.11.1.min.js"></script>
<script src="/Scripts/jquery-ui.min.js"></script>
<link rel="stylesheet" href="/Contents/jquery-ui.min.css" />
@{
    ViewBag.Title = "EditEmpty";
    Layout = "~/Views/Share/Index.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Chỉnh sửa</title>
</head>
<body>
    <div class="main">
        <div class="info-addnew">
            <form method="post" class="form-horizontal" action="/Bo/EditEmpty">

                @foreach (var item in Model.Bos)
                {
                    <div class="form-group">
                        <div class="col-sm-4">
                            <input type="hidden" name="bo.MaBo" id="bo.MaBo" value='@item.MaBo' class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Kí Hiệu</label>
                        <div class="col-sm-4">
                            <input type="text" name="bo.KiHieu" id="bo.KiHieu" value='@item.KiHieu' class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Lớp</label>
                        <div class="col-sm-4">
                            <input type="text" name="Bo.Lop" id="Bo.Lop" value='@item.Lop' class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Danh pháp khoa học</label>
                        <div class="col-sm-4">
                            <input type="text" name="bo.DPKH" id="bo.DPKH" value='@item.DPKH' class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Tên Tiếng Việt</label>
                        <div class="col-sm-4">
                            <input type="text" name="bo.TenTV" id="bo.TenTV" value='@item.TenTV' class="form-control" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Người phát hiện</label>
                        <div class="col-sm-4">
                            <input type="text" name="bo.NguoiPH" id="bo.NguoiPH" value='@item.NguoiPH' class="form-control" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Năm phát hiện</label>
                        <div class="col-sm-4">
                            <input type="text" name="bo.NamPH" id="bo.NamPH" value='@item.NamPH' class="form-control" data-val="true" data-val-year="The field Release Date must be a date." data-val-required="The Release Date field is required." />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-4">
                            <input type="hidden" name="bo.TenNguoiTao" id="bo.TenNguoiTao" value='@item.TenNguoiTao' class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-4">
                            <input type="hidden" name="bo.MaNguoiTao" id="bo.MaNguoiTao" value='@item.MaNguoiTao' class="form-control" />
                        </div>
                    </div>
                }
                <div class="form-group">
                    <label class="col-sm-2 control-label"></label>
                    <div class="col-sm-4">
                        <input type="submit" class="btn btn-default" style="float:right;" value="Submit" />
                    </div>
                </div>

       
            </form>
            </div>
            <div>
                @Html.ActionLink("Back to List", "IndexBo")
            </div>
        </div>
</body>

</html>

Backup/FinalDemo/Views/Bo/IndexBo.cshtml
@model FinalDemo.Models.BoViewModel
<link rel="stylesheet" href="/Contents/bootstrap.min.css" />
<script src="~/Scripts/jquery-ui.js"></script>
<script src="~/Scripts/jquery-ui.min.js"></script>
<link rel="stylesheet" href="/Contents/jquery-ui.min.css" />
<script type="text/javascript">
    $(function () {
        $("#txtSearch").autocomplete({
            source: '@Url.Action("SearchAuto")',
            minLenght: 2
        });
    });
</script>

<body>
    @{
        ViewBag.Title = "Thông tin Bộ";
        Layout = "~/Views/Share/Index.cshtml";
    }
    <div class="main">
        <div class="search">
            @using (Html.BeginForm())
            {
                @Html.TextBox("searchTerm", null, new { id = "txtSearch" })
                <input type="submit" value="Tìm Kiếm" />
            }


        </div>
        <div class="table-responsive">
            <table class="table">

                <tr>
                    <th>
                        Danh pháp khoa học
                    </th>
                    <th>
                        Tên tiếng việt
                    </th>
                    <th>
                        Người phát hiện
                    </th>
                    <th>
                        Năm phát hiện
                    </th>
                </tr>

                @foreach (var item in Model.Bos)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.DPKH)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TenTV)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NguoiPH)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NamPH)
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
</body>

Backup/FinalDemo/Views/Bo/Search.cshtml
@model FinalDemo.Models.BoViewModel
<link rel="stylesheet" href="/Contents/bootstrap.min.css" />
<script src="/Scripts/jquery-1.11.1.min.js"></script>
<script src="/Scripts/jquery-ui.min.js"></script>
<link rel="stylesheet" href="/Contents/jquery-ui.min.css" />

@{
    ViewBag.Title = "Tìm kiếm";
    Layout = "~/Views/Share/Index.cshtml";
}

<p>
    @Html.ActionLink("CreateNew", "CreateNewBo")
</p>
<form method="post" action="/Bo/Search">
    <input type="text" name="find" id="find" placeholder="Find">
    <input type="submit" value="Search" />
    <table class="table table-hover">
        <tr>
            <th>
                Kí hiệu
            </th>
            <th>
                Danh pháp khoa học
            </th>
            <th>
                Tên tiếng việt
            </th>
            <th>
                Người phát hiện
            </th>
            <th>
                Năm phát hiện
            </th>
        </tr>

        @foreach (var item in Model.Bos)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.KiHieu)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DPKH)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TenTV)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NguoiPH)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NamPH)
                </td>
                <td>
                    @Html.ActionLink("Edit", "EditEmpty", new { id = item.MaBo }) |
                    @Html.ActionLink("Details", "Details", new { id = item.MaBo }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.MaBo })
                </td>
            </tr>
        }

    </table>
</form>

Backup/FinalDemo/Views/Bo/SignInOutPanel.cshtml
@model AuthTool.TaiKhoan

@{
    if (Model != null)
    {
        <p class="btn btn-default navbar-btn">@Model.Ten</p>
        <a class="btn btn-default navbar-btn" href="/Home/SignOutUser">Đăng xuất</a>
    }
    else
    {
        <a class="btn btn-default navbar-btn" href="/NguoiDung/Index">Đăng nhập\Tạo tài khoản</a>
    }
}