FinalDemo/Models/ThongKeViewModel.cs
using FinalDemo.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FinalDemo.Models
{
    public class ThongKeViewModel
    {
        public List<ThongKe> ThongKes;
    }
}

FinalDemo/Controllers/ThongKeController.cs
using CrystalDecisions.CrystalReports.Engine;
using FinalDemo.Domain.Abtracts;
using FinalDemo.Domain.Entities;
using FinalDemo.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace FinalDemo.Controllers
{
    public class ThongKeController : BaseController
    {
        //
        // GET: /ThongKe/
        private IThongKeRepository repositoryT { get; set; }
        private ILopRepository repositoryL { get; set; }
        private IBoRepository repositoryB { get; set; }
        public ThongKeController(IThongKeRepository repoT, ILopRepository repoL, IBoRepository repoB)
        {
            repositoryT = repoT;
            repositoryL = repoL;
            repositoryB = repoB;
            base.Init();
        }
        public ActionResult IndexThongKe()
        {
            return View();
        }
        public PartialViewResult SignInOutPanel()
        {
            return PartialView(base.CurrentUser);
        }
        public ActionResult GetAllLops()
        {
            LopViewModel lopView = new LopViewModel();
            StringBuilder sb = new StringBuilder();
            lopView.Lops = repositoryL.GetAllLop();
            foreach (Lop viewLop in lopView.Lops)
            {
                sb.AppendFormat("<option value='{0}'>{1}</option>", viewLop.MaLop, viewLop.TenTV);
            }
            Response.Write(sb);
            return null;
        }
        public ActionResult GetThongKeByLop(int Lop)
        {
            ThongKeViewModel thongkeView = new ThongKeViewModel();
            StringBuilder sb = new StringBuilder();
            sb.Append("<table border='1'>");
            sb.Append("<tr><td>Mã Bộ</td><td>Tên Tiếng Việt</td><td>Họ</td><td>%</td><td>Chi</td><td>%</td><td>Loài</td><td>%</td></tr>");
            thongkeView.ThongKes = repositoryT.GetThongKeByLop(Lop);
            foreach (ThongKe tk in thongkeView.ThongKes)
            {
                sb.AppendFormat("<tr><td>{0}</td><td>{1}</td><td>{2}</td><td>{3}</td><td>{4}</td><td>{5}</td><td>{6}</td><td>{7}</td></tr>"
                    , tk.MaBo, tk.TenTiengViet, tk.Ho, tk.perHo, tk.Chi, tk.perChi, tk.Loai, tk.perLoai);
            }
            sb.Append("</table>");
            Response.Write(sb.ToString());
            return null;
        }
        public ActionResult Report(int Lop)
        {
            ReportClass rptH = new ReportClass();
            ThongKeViewModel thongkeView = new ThongKeViewModel();
            thongkeView.ThongKes = repositoryT.GetThongKeByLop(Lop);
            
            rptH.FileName = Server.MapPath("/Reporting/crystalReport.rpt");

            rptH.Load();
            //rptH.SetParameterValue("@Lop", Lop);
            rptH.SetDataSource(thongkeView.ThongKes);

            Stream stream = rptH.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);

            return File(stream, "application/pdf"); 
        }
        public ActionResult Test()
        {
            LopViewModel lopView = new LopViewModel();
            lopView.Lops = repositoryL.GetAllLop();
            ViewBag.ListOfCodes = new SelectList(lopView.Lops, "MaLop", "TenTV");
            ViewBag.Codes = "C";
            return View();
        }
        }
}

FinalDemo/Views/ThongKe/IndexThongKe.cshtml
@{
    ViewBag.Title = "Thống kê";
    Layout = "~/Views/Share/Index.cshtml";
}

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Thống kê</title>
    <script src="/Scripts/jquery-1.11.1.min.js"></script>
    <script src="/Scripts/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="/Contents/jquery-ui.min.css" />
    <link rel="stylesheet" href="/Contents/bootstrap.min.css" />
</head>

<body>
    <button type="button" data-toggle="collapse" data-target="#demo" onclick="addButtonClick()">Xem thống kê theo lớp</button>
    <div id="demo" class="collapse">
        <select id="cbbLop" onchange="cbbLopChange();">
            <option value="">Chọn Lớp</option>
        </select>
        <div id="tableThongKe">

        </div>
               
    </div>  
    <a href="@Url.Action("Report")">Generate User Report</a>     
    <script>
        //<a href="/ThongKe/Report">ShowReport</a>
            function addButtonClick() {
                $("#cbbLop").html("<option value=''>Chọn Lớp</option>");
                $.ajax({
                    type: "POST",
                    url: "/ThongKe/GetAllLops",
                })
                .done(function (msg) {
                    $("#cbbLop").html($("#cbbLop").html() + msg);
                });
            }
            $(document).ready(function () {
                window.setInterval(function () { cbbLopChange('/ThongKe/GetThongKeByLop', $("#tableThongKe")); }, 1000);
                window.setInterval(function () { cbbLopChange('/ThongKe/Report', null); }, 1000);
            });

            var cbbLopChange = function (page, ele) {
                var Lop = $("#cbbLop").val();
                $.ajax({
                    type: "POST",
                    url: page,
                    data: {
                        Lop: Lop,
                    }
                })
                .done(function (msg) {
                    ele.html(msg);
                });
            };
            //function cbbLopChange() {
            //    var Lop = $("#cbbLop").val();
            //    $.ajax({
            //        type: "POST",
            //        url: "/ThongKe/GetThongKeByLop",
            //        data: {
            //            Lop: Lop,
            //        }
            //    })
            //    .done(function (msg) {
            //        $("#tableThongKe").html(msg);
            //    });
            //}
    </script>
    <script src="/Scripts/bootstrap.min.js"></script>
</body>
</html>

FinalDemo/Views/ThongKe/SignInOutPanel.cshtml
@model AuthTool.TaiKhoan

@{
    if (Model != null)
    {
        <p class="btn btn-default navbar-btn">@Model.Ten</p>
        <a class="btn btn-default navbar-btn" href="/Home/SignOutUser">Đăng xuất</a>
    }
    else
    {
        <a class="btn btn-default navbar-btn" href="/NguoiDung/Index">Đăng nhập\Tạo tài khoản</a>
    }
}

FinalDemo/Views/ThongKe/Test.cshtml
@model FinalDemo.Domain.Entities.Bo
@{
    ViewBag.Title = "Test";
    Layout = "~/Views/Share/Index.cshtml";
}

@using (Html.BeginForm("Report", "ThongKe", FormMethod.Get))
{

    <fieldset>

        <div class="editor-field">
            @Html.DropDownListFor(model => model.Lop, ViewBag.ListOfCodes as SelectList, "")
            @Html.ValidationMessageFor(model => model.Lop)

        </div>

        <p>

            <input type="submit" value="Submit" />

        </p>

    </fieldset>

} 